server:
  http_listen_port: 9080
  grpc_listen_port: 0

positions:
  filename: /tmp/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
- job_name: systemdlogs
  static_configs:
  - targets:
      - localhost
    labels:
      job: terraform-management-console-backend
      __path__: /var/log/terraform-management-console-backend.log
- job_name: container_logs 
  docker_sd_configs:
    - host: unix:///var/run/docker.sock
      refresh_interval: 5s
        #filters:
        #- name: name
        #values: [flog] 
  relabel_configs:
    - source_labels: ['__meta_docker_container_name']
      regex: '/(.*)'
      target_label: 'container'
